on:
  workflow_dispatch:
  schedule:
    - cron: "*/2 7-22 * * *"
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: "1"

jobs:
  generate-times:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable --profile minimal
      - uses: Swatinem/rust-cache@v2
        with:
          cache-all-crates: "true"
      - name: Generate times and push to Tidbyt
        env:
          BUS_STOP_NAPTAN_CODE: ${{ secrets.BUS_STOP_NAPTAN_CODE }}
          MINUTES_AWAY: ${{ secrets.MINUTES_AWAY }}
          NEXT_BUSES_API_PASS: ${{ secrets.NEXT_BUSES_API_PASS }}
          NEXT_BUSES_API_USER: ${{ secrets.NEXT_BUSES_API_USER }}
          TIDBYT_ID: ${{ secrets.TIDBYT_ID }}
          TIDBYT_KEY: ${{ secrets.TIDBYT_KEY }}
          OUTPUT_TIMEZONE: ${{ secrets.OUTPUT_TIMEZONE }}
        run: cargo run
